### ISSUE TITLE
date: unrecognized option '--iso-8601'

### ISSUE THREAD

**Issue by mattlamb99** [SignalK/set-system-time#11]
I'm running signalk on a [Victron Venus GX,](https://www.victronenergy.com/media/pg/Venus_GX/en/index-en.html) which is a beaglebone board. I'm getting the follwing error in signalk:
`@signalk/set-system-time:date: unrecognized option '--iso-8601' BusyBox v1.31.1 (2021-12-17 08:58:32 UTC) multi-call binary. Usage: date [OPTIONS] [+FMT] [TIME]`

I assume this is due to a slightly different binary in this busybox install.

**Comment by tkurki** [comment]
Apparently setting the time on Venus OS is not as simple as executing `date` command.

Venus devices have a real time clock and you can set the time from the UI, so there should be much less use for this utility. Do you really need it?
