### ISSUE TITLE
Feature request: Time server

### ISSUE THREAD

**Issue by NAHANNIV** [SignalK/set-system-time#8]
Provide a time server for connected devices.
Usefull when not internet connected.

**Comment by tkurki** [comment]
I think this is beyond the scope of this plugin. You imagine you can configure your Linux machine to act as a time server and just rely on this plugin to set the time, but can't really offer any assistance with that.

**Comment by tkurki** [comment]
That was supposed to read _I imagine you can configure..._.

**Comment by NAHANNIV** [comment]
Ok, thanks.. I will ask if OpenPlotter can add an easy way to configure a time server.
